<a href="https://colab.research.google.com/github/SunainaMandal28/Amazon-/blob/main/Day_1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [ ]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [ ]:
ones = np.ones(5)
print(ones.dtype)

float64


In [ ]:
ones = np.ones(5)
print(type(ones))

<class 'numpy.ndarray'>


In [ ]:
arr1 = np.arange(8)
print(arr1)

[0 1 2 3 4 5 6 7]


In [ ]:
arr1 = np.arange(3,8)
print(arr1)

[3 4 5 6 7]


In [ ]:
arr1 = np.arange(2,10,2) #Even
print(arr1)

[2 4 6 8]


In [ ]:
arr1 =np.arange(3)
arr2 =np.arange(3)
print(arr1,arr2)

[0 1 2] [0 1 2]


In [ ]:
print (arr1 + arr2)

[0 2 4]


In [ ]:
print (arr1 - arr2)

[0 0 0]


In [ ]:
print (arr1 * arr2)

[0 1 4]


In [ ]:
arr1 =np.arange(4)
arr2 =np.arange(4)
print (arr1/arr2)

[nan  1.  1.  1.]


/tmp/ipython-input-1353368895.py:3: RuntimeWarning: invalid value encountered in divide
  print (arr1/arr2)
